spring.datasource.url: jdbc:mysql://localhost:3306/diplombox?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 12345678
spring.jpa.hibernate.ddl-auto: update

#update
#create-drop
#create

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 51200KB
      max-request-size: 51200KB


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 999 777-33-44
  email: mail@mail.ru
  copyright: Алексеев Антон
  copyrightFrom: 2005


